### ISSUE TITLE
Document docker action usage

### ISSUE THREAD

**Issue by aplr** [ariga/atlas-deploy-action#8]
Quite a edge-case probably, but an easy fix if documented.

I'm running [cloud-sql-proxy](https://github.com/GoogleCloudPlatform/cloud-sql-proxy) in combination with [tailscale](https://tailscale.com/) to access my postgres instance w/ private address in Google Cloud.

The proxy exposes the connection on a port on the github runner's localhost.

As this action runs in a docker container itself, connecting to localhost, does of course not connect to the github runner's "localhost".

The fix is using `172.17.0.1` as a host, instead of `localhost`:

```
- name: Deploy Atlas Migrations
  uses: ariga/atlas-deploy-action@v0
  env:
    DB_HOST: "172.17.0.1"
    DB_PORT: "1234"
    DB_USERNAME: pg
    DB_PASSWORD: pg
    DB_NAME: pg
  with:
    url: postgres://${{ env.DB_USERNAME }}:${{ env.DB_PASSWORD }}@${{ env.DB_HOST }}:${{ env.DB_PORT }}/${{ env.DB_NAME }}?search_path=public&sslmode=disable
```

Probably it'd be good to document that this action is running in a docker container, as I was looking too long on my end.
And also, how to connect to localhost then.
